# Project: Led
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = LED_CALCULO.o
LINKOBJ  = LED_CALCULO.o
LIBS     = -L"C:/Users/SAM/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/SAM/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/SAM/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/SAM/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/SAM/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/SAM/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/SAM/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/SAM/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/SAM/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Led_calculo.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

LED_CALCULO.o: LED_CALCULO.c
	$(CC) -c LED_CALCULO.c -o LED_CALCULO.o $(CFLAGS)
